# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-06 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncommercialeapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailapprovisionnement',
            name='approvisionnement',
            field=models.ManyToManyField(related_name='approvisionnement', to='gestioncommercialeapi.Approvisionnement'),
        ),
        migrations.AddField(
            model_name='detailapprovisionnement',
            name='produit',
            field=models.ManyToManyField(related_name='produit', to='gestioncommercialeapi.Produit'),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='commande',
            field=models.ManyToManyField(related_name='commande', to='gestioncommercialeapi.Commande'),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='produit',
            field=models.ManyToManyField(related_name='produit_list', to='gestioncommercialeapi.Produit'),
        ),
        migrations.RemoveField(
            model_name='facturefournisseur',
            name='approvisionnement',
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='approvisionnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnement_id', to='gestioncommercialeapi.DetailApprovisionnement'),
        ),
        migrations.AlterUniqueTogether(
            name='detailapprovisionnement',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='detailcommande',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='detailapprovisionnement',
            name='approvisionnement',
        ),
        migrations.RemoveField(
            model_name='detailapprovisionnement',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='detailcommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='detailcommande',
            name='produit',
        ),
    ]
