# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-18 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncommercialeapi', '0002_auto_20181106_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailapprovisionnement',
            name='approvisionnement',
            field=models.ManyToManyField(related_name='approvisionnement', to='gestioncommercialeapi.Approvisionnement'),
        ),
        migrations.AddField(
            model_name='detailapprovisionnement',
            name='produit',
            field=models.ManyToManyField(related_name='produit', to='gestioncommercialeapi.Produit'),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='commande',
            field=models.ManyToManyField(related_name='commande', to='gestioncommercialeapi.Commande'),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='produit',
            field=models.ManyToManyField(related_name='produit_list', to='gestioncommercialeapi.Produit'),
        ),
    ]
